# Generated by Django 5.1.4 on 2025-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
